[26-Jul-2024 21:03:20 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[26-Jul-2024 21:03:20 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[28-Jul-2024 18:53:26 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[28-Jul-2024 18:53:26 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 06:06:15 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 06:06:15 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:22:19 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:22:19 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:35:11 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:35:11 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:35:11 UTC] PHP Warning:  stream_socket_client(): Unable to connect to tcp://127.0.0.1:29092 (Connection refused) in /var/www/public/vendor/longlang/phpkafka/src/Socket/StreamSocket.php on line 84
[29-Jul-2024 21:35:11 UTC] PHP Fatal error:  Uncaught longlang\phpkafka\Exception\ConnectionException: Could not connect to tcp://127.0.0.1:29092 (Connection refused [111]) in /var/www/public/vendor/longlang/phpkafka/src/Socket/StreamSocket.php:94
Stack trace:
#0 /var/www/public/vendor/longlang/phpkafka/src/Client/SyncClient.php(101): longlang\phpkafka\Socket\StreamSocket->connect()
#1 /var/www/public/vendor/longlang/phpkafka/src/Broker.php(88): longlang\phpkafka\Client\SyncClient->connect()
#2 /var/www/public/vendor/longlang/phpkafka/src/Producer/Producer.php(40): longlang\phpkafka\Broker->updateBrokers()
#3 /var/www/public/index.php(13): longlang\phpkafka\Producer\Producer->__construct(Object(longlang\phpkafka\Producer\ProducerConfig))
#4 {main}
  thrown in /var/www/public/vendor/longlang/phpkafka/src/Socket/StreamSocket.php on line 94
[29-Jul-2024 21:35:13 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:35:13 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:35:13 UTC] PHP Warning:  stream_socket_client(): Unable to connect to tcp://127.0.0.1:29092 (Connection refused) in /var/www/public/vendor/longlang/phpkafka/src/Socket/StreamSocket.php on line 84
[29-Jul-2024 21:35:13 UTC] PHP Fatal error:  Uncaught longlang\phpkafka\Exception\ConnectionException: Could not connect to tcp://127.0.0.1:29092 (Connection refused [111]) in /var/www/public/vendor/longlang/phpkafka/src/Socket/StreamSocket.php:94
Stack trace:
#0 /var/www/public/vendor/longlang/phpkafka/src/Client/SyncClient.php(101): longlang\phpkafka\Socket\StreamSocket->connect()
#1 /var/www/public/vendor/longlang/phpkafka/src/Broker.php(88): longlang\phpkafka\Client\SyncClient->connect()
#2 /var/www/public/vendor/longlang/phpkafka/src/Producer/Producer.php(40): longlang\phpkafka\Broker->updateBrokers()
#3 /var/www/public/index.php(13): longlang\phpkafka\Producer\Producer->__construct(Object(longlang\phpkafka\Producer\ProducerConfig))
#4 {main}
  thrown in /var/www/public/vendor/longlang/phpkafka/src/Socket/StreamSocket.php on line 94
[29-Jul-2024 21:36:56 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:36:56 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:39:41 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:39:41 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:39:59 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:39:59 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:40:02 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:40:02 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:40:03 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:40:03 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:40:03 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:40:03 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:40:03 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:40:03 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:41:37 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:41:37 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:41:38 UTC] PHP Fatal error:  Uncaught longlang\phpkafka\Exception\KafkaErrorException: [82] The broker rejected this static consumer since another consumer with the same group.instance.id has registered with a different member.id. in /var/www/public/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php:385
Stack trace:
#0 /var/www/public/vendor/longlang/phpkafka/src/Util/KafkaUtil.php(84): longlang\phpkafka\Protocol\ErrorCode::check(82)
#1 /var/www/public/vendor/longlang/phpkafka/src/Group/GroupManager.php(123): longlang\phpkafka\Util\KafkaUtil::retry(Object(longlang\phpkafka\Client\SyncClient), Object(longlang\phpkafka\Protocol\Heartbeat\HeartbeatRequest), 0, 0.01)
#2 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(409): longlang\phpkafka\Group\GroupManager->heartbeat('testGroup', 'test', 'test-7fb5d58d-4...', 1)
#3 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(426): longlang\phpkafka\Consumer\Consumer->heartbeat()
#4 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(294): longlang\phpkafka\Consumer\Consumer->checkBeartbeat()
#5 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(248): longlang\phpkafka\Consumer\Consumer->fetchMessages()
#6 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(224): longlang\phpkafka\Consumer\Consumer->consume()
#7 /var/www/public/consumer/asynchronous.php(22): longlang\phpkafka\Consumer\Consumer->start()
#8 {main}
  thrown in /var/www/public/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php on line 385
[29-Jul-2024 21:43:43 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:43:43 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:26 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:26 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:26 UTC] PHP Fatal error:  Uncaught longlang\phpkafka\Exception\KafkaErrorException: [82] The broker rejected this static consumer since another consumer with the same group.instance.id has registered with a different member.id. in /var/www/public/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php:385
Stack trace:
#0 /var/www/public/vendor/longlang/phpkafka/src/Util/KafkaUtil.php(84): longlang\phpkafka\Protocol\ErrorCode::check(82)
#1 /var/www/public/vendor/longlang/phpkafka/src/Group/GroupManager.php(123): longlang\phpkafka\Util\KafkaUtil::retry(Object(longlang\phpkafka\Client\SyncClient), Object(longlang\phpkafka\Protocol\Heartbeat\HeartbeatRequest), 0, 0.01)
#2 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(409): longlang\phpkafka\Group\GroupManager->heartbeat('testGroup', 'test_custom', 'test_custom-1a5...', 2)
#3 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(426): longlang\phpkafka\Consumer\Consumer->heartbeat()
#4 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(294): longlang\phpkafka\Consumer\Consumer->checkBeartbeat()
#5 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(248): longlang\phpkafka\Consumer\Consumer->fetchMessages()
#6 /var/www/public/consumer/synchronous.php(16): longlang\phpkafka\Consumer\Consumer->consume()
#7 {main}
  thrown in /var/www/public/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php on line 385
[29-Jul-2024 21:47:28 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:28 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:30 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:30 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:30 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:30 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:31 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:31 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:31 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:31 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:31 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:31 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:32 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:32 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:34 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:34 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:34 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:34 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:34 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:34 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:34 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:34 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:34 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:34 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:35 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:35 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:35 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:35 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:39 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:39 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:39 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:39 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:39 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:39 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:39 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:39 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:40 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:40 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:40 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:40 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:47:40 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:47:40 UTC] Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port).
[29-Jul-2024 21:50:55 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:51:36 UTC] PHP Fatal error:  Uncaught longlang\phpkafka\Exception\KafkaErrorException: [82] The broker rejected this static consumer since another consumer with the same group.instance.id has registered with a different member.id. in /var/www/public/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php:385
Stack trace:
#0 /var/www/public/vendor/longlang/phpkafka/src/Util/KafkaUtil.php(84): longlang\phpkafka\Protocol\ErrorCode::check(82)
#1 /var/www/public/vendor/longlang/phpkafka/src/Group/GroupManager.php(123): longlang\phpkafka\Util\KafkaUtil::retry(Object(longlang\phpkafka\Client\SyncClient), Object(longlang\phpkafka\Protocol\Heartbeat\HeartbeatRequest), 0, 0.01)
#2 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(409): longlang\phpkafka\Group\GroupManager->heartbeat('testGroup', 'test_custom', 'test_custom-78a...', 2)
#3 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(426): longlang\phpkafka\Consumer\Consumer->heartbeat()
#4 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(294): longlang\phpkafka\Consumer\Consumer->checkBeartbeat()
#5 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(248): longlang\phpkafka\Consumer\Consumer->fetchMessages()
#6 /var/www/public/consumer/synchronous.php(16): longlang\phpkafka\Consumer\Consumer->consume()
#7 {main}
  thrown in /var/www/public/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php on line 385
[29-Jul-2024 21:51:49 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:31 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:44 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:45 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:45 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:45 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:45 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:45 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:46 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:46 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:46 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:47 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:47 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:47 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:47 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:47 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:47 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:48 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:52:48 UTC] Xdebug: [Log Files] File '/var/log/xdebug/xdebug.log' could not be opened.
[29-Jul-2024 21:54:37 UTC] PHP Fatal error:  Uncaught longlang\phpkafka\Exception\SocketException: Unexpected EOF while reading 4 bytes from stream (no data) in /var/www/public/vendor/longlang/phpkafka/src/Socket/StreamSocket.php:211
Stack trace:
#0 /var/www/public/vendor/longlang/phpkafka/src/Client/SyncClient.php(170): longlang\phpkafka\Socket\StreamSocket->recv(4)
#1 /var/www/public/vendor/longlang/phpkafka/src/Client/SyncClient.php(187): longlang\phpkafka\Client\SyncClient->recv(1219, NULL)
#2 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(328): longlang\phpkafka\Client\SyncClient->sendRecv(Object(longlang\phpkafka\Protocol\Fetch\FetchRequest))
#3 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(248): longlang\phpkafka\Consumer\Consumer->fetchMessages()
#4 /var/www/public/vendor/longlang/phpkafka/src/Consumer/Consumer.php(224): longlang\phpkafka\Consumer\Consumer->consume()
#5 /var/www/public/consumer/asynchronous.php(22): longlang\phpkafka\Consumer\Consumer->start()
#6 {main}
  thrown in /var/www/public/vendor/longlang/phpkafka/src/Socket/StreamSocket.php on line 211
